import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { z } from "zod"
import { writeDoc } from "../../storage/index.js"
import { createLogger } from "../../utils/logger.js"
import { existsSync } from "node:fs"
import { basename } from "node:path"

const logger = createLogger("mcp:codegraph-tools")

interface SpawnResult {
  stdout: string
  stderr: string
  exitCode: number
}

async function runCodegraph(args: string[], cwd: string, timeoutMs: number): Promise<SpawnResult> {
  const proc = Bun.spawn(["codegraph", ...args], {
    cwd,
    stdout: "pipe",
    stderr: "pipe",
    env: { ...process.env },
  })

  const exitCode = await Promise.race([
    proc.exited,
    new Promise<number>((_, reject) =>
      setTimeout(() => {
        proc.kill()
        reject(new Error(`codegraph timed out after ${timeoutMs}ms`))
      }, timeoutMs),
    ),
  ])

  const stdout = await new Response(proc.stdout).text()
  const stderr = await new Response(proc.stderr).text()

  return { stdout, stderr, exitCode }
}

function parseJsonSafe(raw: string): unknown {
  try {
    return JSON.parse(raw)
  } catch {
    return null
  }
}

function buildOverviewMarkdown(projectName: string, status: any): string {
  const lines: string[] = []
  lines.push(`# ${projectName} — Code Architecture Overview`)
  lines.push("")

  const stats = status.stats || status
  lines.push("## Stats")
  lines.push(`- Files: ${stats.files ?? stats.fileCount ?? "N/A"}`)
  lines.push(`- Nodes: ${stats.nodes ?? stats.nodeCount ?? "N/A"}`)
  lines.push(`- Edges: ${stats.edges ?? stats.edgeCount ?? "N/A"}`)
  if (stats.languages) lines.push(`- Languages: ${Array.isArray(stats.languages) ? stats.languages.join(", ") : stats.languages}`)
  if (stats.dbSize) lines.push(`- DB Size: ${stats.dbSize}`)
  if (stats.indexedAt) lines.push(`- Indexed At: ${stats.indexedAt}`)
  lines.push("")

  if (stats.languageBreakdown || stats.languages_detail) {
    const langs = stats.languageBreakdown || stats.languages_detail || []
    if (Array.isArray(langs) && langs.length > 0) {
      lines.push("## Languages")
      lines.push("| Language | Files | Nodes |")
      lines.push("|----------|-------|-------|")
      for (const lang of langs) {
        lines.push(`| ${lang.language || lang.name} | ${lang.files ?? lang.fileCount ?? 0} | ${lang.nodes ?? lang.nodeCount ?? 0} |`)
      }
      lines.push("")
    }
  }

  if (stats.nodeKinds || stats.kindBreakdown) {
    const kinds = stats.nodeKinds || stats.kindBreakdown || []
    if (typeof kinds === "object" && !Array.isArray(kinds)) {
      lines.push("## Node Distribution")
      lines.push("| Kind | Count |")
      lines.push("|------|-------|")
      for (const [kind, count] of Object.entries(kinds)) {
        lines.push(`| ${kind} | ${count} |`)
      }
      lines.push("")
    } else if (Array.isArray(kinds)) {
      lines.push("## Node Distribution")
      lines.push("| Kind | Count |")
      lines.push("|------|-------|")
      for (const k of kinds) {
        lines.push(`| ${k.kind || k.name} | ${k.count} |`)
      }
      lines.push("")
    }
  }

  lines.push("## Raw Status")
  lines.push("```json")
  lines.push(JSON.stringify(status, null, 2))
  lines.push("```")
  lines.push("")
  lines.push("---")
  lines.push("> Auto-generated by kb_ingest_codegraph")
  return lines.join("\n")
}

function buildModuleMarkdown(projectName: string, status: any, files: any[]): string {
  const lines: string[] = []
  lines.push(`# ${projectName} — Module Breakdown`)
  lines.push("")

  if (Array.isArray(files)) {
    for (const file of files) {
      const fp = file.path || file.filePath || file.name || "unknown"
      lines.push(`## ${fp}`)
      lines.push(`- Language: ${file.language || "unknown"}`)
      lines.push(`- Node count: ${file.nodeCount ?? file.nodes ?? file.symbolCount ?? 0}`)
      if (file.classes && Array.isArray(file.classes) && file.classes.length > 0) {
        lines.push(`- Classes: ${file.classes.join(", ")}`)
      }
      if (file.functions && Array.isArray(file.functions) && file.functions.length > 0) {
        lines.push(`- Functions: ${file.functions.join(", ")}`)
      }
      if (file.exports && Array.isArray(file.exports) && file.exports.length > 0) {
        lines.push(`- Exports: ${file.exports.join(", ")}`)
      }
      if (file.symbols && Array.isArray(file.symbols) && file.symbols.length > 0) {
        const fns = file.symbols.filter((s: any) => s.kind === "function" || s.kind === "method").map((s: any) => s.name)
        const cls = file.symbols.filter((s: any) => s.kind === "class").map((s: any) => s.name)
        const exps = file.symbols.filter((s: any) => s.exported).map((s: any) => s.name)
        if (cls.length > 0) lines.push(`- Classes: ${cls.join(", ")}`)
        if (fns.length > 0) lines.push(`- Functions: ${fns.join(", ")}`)
        if (exps.length > 0) lines.push(`- Exports: ${exps.join(", ")}`)
      }
      lines.push("")
    }
  } else {
    lines.push("No file data available from codegraph.")
    lines.push("")
  }

  lines.push("## Raw Data")
  lines.push("```json")
  lines.push(JSON.stringify({ status, files }, null, 2))
  lines.push("```")
  lines.push("")
  lines.push("---")
  lines.push("> Auto-generated by kb_ingest_codegraph")
  return lines.join("\n")
}

function buildSymbolMarkdown(projectName: string, query: string, context: any): string {
  const lines: string[] = []
  lines.push(`# ${projectName} — Symbol Analysis: ${query}`)
  lines.push("")

  if (context.summary) {
    lines.push("## Summary")
    lines.push(context.summary)
    lines.push("")
  }

  if (context.entryPoints && Array.isArray(context.entryPoints) && context.entryPoints.length > 0) {
    lines.push("## Entry Points")
    for (const ep of context.entryPoints) {
      lines.push(`- ${ep.name || ep} (${ep.kind || "unknown"}) at ${ep.file || ""}:${ep.line || ""}`)
    }
    lines.push("")
  }

  if (context.symbols && Array.isArray(context.symbols) && context.symbols.length > 0) {
    lines.push("## Key Symbols")
    for (const sym of context.symbols.slice(0, 30)) {
      lines.push(`### ${sym.name} (${sym.kind || "unknown"})`)
      if (sym.signature) lines.push(`- Signature: \`${sym.signature}\``)
      if (sym.file || sym.location) {
        const loc = sym.location || sym.file
        lines.push(`- Location: ${typeof loc === "string" ? loc : `${loc.file || sym.file}:${loc.line || ""}`}`)
      }
      if (sym.exported !== undefined) lines.push(`- Exported: ${sym.exported}`)
      lines.push("")
    }
  }

  if (context.codeBlocks && Array.isArray(context.codeBlocks) && context.codeBlocks.length > 0) {
    lines.push("## Code Blocks")
    for (const block of context.codeBlocks.slice(0, 15)) {
      const loc = block.file ? `${block.file}:${block.startLine || ""}-${block.endLine || ""}` : "unknown"
      lines.push(`### ${loc}`)
      lines.push(`\`\`\`${block.language || ""}`)
      lines.push(block.content || block.code || "")
      lines.push("```")
      lines.push("")
    }
  }

  if (context.dependencies && Array.isArray(context.dependencies) && context.dependencies.length > 0) {
    lines.push("## Dependencies")
    for (const dep of context.dependencies) {
      lines.push(`- ${typeof dep === "string" ? dep : dep.path || dep.file || JSON.stringify(dep)}`)
    }
    lines.push("")
  }

  if (context.stats) {
    lines.push("## Stats")
    const s = context.stats
    lines.push(`- Nodes: ${s.nodes ?? "N/A"}, Edges: ${s.edges ?? "N/A"}, Files: ${s.files ?? "N/A"}, Code Size: ${s.codeSize ?? "N/A"}`)
    lines.push("")
  }

  lines.push("## Raw Context")
  lines.push("```json")
  lines.push(JSON.stringify(context, null, 2))
  lines.push("```")
  lines.push("")
  lines.push("---")
  lines.push("> Auto-generated by kb_ingest_codegraph")
  return lines.join("\n")
}

function extractKeywords(projectName: string, status: any, files?: any[]): string[] {
  const kw = new Set<string>()
  kw.add(projectName)
  if (status.stats?.languages) {
    const langs = Array.isArray(status.stats.languages) ? status.stats.languages : [status.stats.languages]
    for (const l of langs) kw.add(String(l))
  }
  if (status.stats?.languageBreakdown) {
    for (const l of status.stats.languageBreakdown) kw.add(l.language || l.name)
  }
  if (files && Array.isArray(files)) {
    const dirs = new Set<string>()
    for (const f of files.slice(0, 50)) {
      const fp = f.path || f.filePath || f.name || ""
      const parts = fp.split("/")
      if (parts.length > 1) dirs.add(parts[0])
    }
    for (const d of dirs) kw.add(d)
  }
  return [...kw].filter(k => k.length > 0).slice(0, 12)
}

function extractRelatedFiles(files: any[]): string[] {
  if (!Array.isArray(files)) return []
  return files
    .map((f: any) => f.path || f.filePath || f.name || "")
    .filter((p: string) => p.length > 0)
    .slice(0, 50)
}

export function registerCodegraphTools(server: McpServer) {
  server.tool(
    "kb_ingest_codegraph",
    "Analyze a project's code structure using the codegraph CLI and write structured summaries into the knowledge base as searchable documents.",
    {
      project_path: z.string().describe("Absolute path to the project to analyze"),
      scope: z.enum(["overview", "module", "symbol"]).default("overview").describe("Level of detail: overview, module, or symbol"),
      query: z.string().optional().describe("Specific query for codegraph context command (used with symbol scope)"),
      force_reindex: z.boolean().default(false).describe("Whether to re-run codegraph index before querying"),
    },
    async (args) => {
      const { project_path, scope, query, force_reindex } = args

      if (!existsSync(project_path)) {
        return {
          content: [{ type: "text", text: JSON.stringify({ error: "Project path does not exist", path: project_path }) }],
        }
      }

      const hasCodegraphDir = existsSync(`${project_path}/.codegraph`)

      try {
        if (force_reindex || !hasCodegraphDir) {
          const initResult = await runCodegraph(
            hasCodegraphDir ? [] : ["init", "-i"],
            project_path,
            60000,
          )
          if (!hasCodegraphDir && initResult.exitCode !== 0) {
            return {
              content: [{
                type: "text",
                text: JSON.stringify({ error: "codegraph init failed", stderr: initResult.stderr, exitCode: initResult.exitCode }),
              }],
            }
          }

          if (force_reindex) {
            const indexResult = await runCodegraph(["index", "-f"], project_path, 60000)
            if (indexResult.exitCode !== 0) {
              logger.warn("codegraph index force-reindex had issues:", indexResult.stderr)
            }
          }
        }

        const projectName = basename(project_path)
        let markdown = ""
        let keywords: string[] = [projectName]
        let relatedFiles: string[] = []
        let statusData: any = null

        if (scope === "overview") {
          const result = await runCodegraph(["status", "--json"], project_path, 30000)
          if (result.exitCode !== 0) {
            return {
              content: [{
                type: "text",
                text: JSON.stringify({ error: "codegraph status failed", stderr: result.stderr, exitCode: result.exitCode }),
              }],
            }
          }
          statusData = parseJsonSafe(result.stdout)
          if (!statusData) {
            statusData = { raw: result.stdout }
          }
          markdown = buildOverviewMarkdown(projectName, statusData)
          keywords = extractKeywords(projectName, statusData)
        } else if (scope === "module") {
          const [statusResult, filesResult] = await Promise.all([
            runCodegraph(["status", "--json"], project_path, 30000),
            runCodegraph(["files", "--json"], project_path, 30000),
          ])

          if (statusResult.exitCode !== 0) {
            return {
              content: [{
                type: "text",
                text: JSON.stringify({ error: "codegraph status failed", stderr: statusResult.stderr }),
              }],
            }
          }

          statusData = parseJsonSafe(statusResult.stdout) || { raw: statusResult.stdout }
          let filesData: any = parseJsonSafe(filesResult.stdout)
          if (!filesData) {
            filesData = []
          }
          if (!Array.isArray(filesData) && (filesData as any).files) {
            filesData = (filesData as any).files
          }

          markdown = buildModuleMarkdown(projectName, statusData, filesData as any[])
          keywords = extractKeywords(projectName, statusData, filesData as any[])
          relatedFiles = extractRelatedFiles(filesData as any[])
        } else {
          const taskQuery = query || `${projectName} project overview`
          const result = await runCodegraph(
            ["context", taskQuery, "--format", "json"],
            project_path,
            30000,
          )
          if (result.exitCode !== 0) {
            const fallbackMd = result.stdout || result.stderr
            if (fallbackMd && !result.stdout.includes("Error")) {
              const doc = writeDoc(
                {
                  title: `CodeGraph: ${projectName} - symbol analysis`,
                  tags: ["code-index", "codegraph", "symbol", "auto-ingested"],
                  keywords: [projectName],
                  intent: `Code structure analysis (symbol) for ${projectName}`,
                  project_description: projectName,
                  project_path,
                  source_project: projectName,
                  related_files: [],
                },
                `# ${projectName} — Symbol Analysis: ${taskQuery}\n\n${fallbackMd}\n\n---\n> Auto-generated by kb_ingest_codegraph`,
              )
              return {
                content: [{
                  type: "text",
                  text: JSON.stringify({
                    saved: true,
                    id: doc.id,
                    title: doc.title,
                    scope: "symbol",
                    project_name: projectName,
                    hint: `Stored symbol analysis for ${projectName}`,
                  }, null, 2),
                }],
              }
            }
            return {
              content: [{
                type: "text",
                text: JSON.stringify({ error: "codegraph context failed", stderr: result.stderr, exitCode: result.exitCode }),
              }],
            }
          }

          let contextData: any = parseJsonSafe(result.stdout)
          if (!contextData) {
            contextData = { raw: result.stdout, summary: result.stdout.slice(0, 500) }
          }
          markdown = buildSymbolMarkdown(projectName, taskQuery, contextData)
          keywords = extractKeywords(projectName, contextData.stats || {})
          if (contextData.dependencies) {
            relatedFiles = contextData.dependencies
              .map((d: any) => typeof d === "string" ? d : d.path || d.file || "")
              .filter((p: string) => p.length > 0)
              .slice(0, 50)
          }
          if (contextData.symbols) {
            const symFiles = contextData.symbols
              .map((s: any) => s.file || (s.location?.file) || "")
              .filter((f: string) => f.length > 0)
            relatedFiles = [...new Set([...relatedFiles, ...symFiles])].slice(0, 50)
          }
        }

        const doc = writeDoc(
          {
            title: `CodeGraph: ${projectName} - ${scope} analysis`,
            tags: ["code-index", "codegraph", scope, "auto-ingested"],
            keywords,
            intent: `Code structure analysis (${scope}) for ${projectName}`,
            project_description: projectName,
            project_path,
            source_project: projectName,
            related_files: relatedFiles,
          },
          markdown,
        )

        return {
          content: [{
            type: "text",
            text: JSON.stringify({
              saved: true,
              id: doc.id,
              title: doc.title,
              scope,
              project_name: projectName,
              keywords,
              related_files_count: relatedFiles.length,
              hint: `Stored ${scope} analysis for ${projectName}`,
            }, null, 2),
          }],
        }
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e)
        if (msg.includes("timed out")) {
          return {
            content: [{
              type: "text",
              text: JSON.stringify({ error: "codegraph command timed out", detail: msg }),
            }],
          }
        }
        return {
          content: [{
            type: "text",
            text: JSON.stringify({ error: "codegraph execution failed", detail: msg }),
          }],
        }
      }
    },
  )
}
