import { describe, it, expect, mock, beforeEach, afterEach } from "bun:test"
import {
  parseJsonSafe,
  buildOverviewMarkdown,
  buildModuleMarkdown,
  buildSymbolMarkdown,
  runCodegraph,
  extractKeywords,
  extractRelatedFiles,
  type CodegraphStatusResult,
  type CodegraphFileResult,
  type CodegraphContextResult,
} from "../src/tools/codegraph-shared"

describe("codegraph-shared", () => {
  describe("parseJsonSafe", () => {
    it("should parse valid JSON", () => {
      expect(parseJsonSafe('{"a":1}')).toEqual({ a: 1 })
    })

    it("should parse valid JSON array", () => {
      expect(parseJsonSafe("[1,2,3]")).toEqual([1, 2, 3])
    })

    it("should return null for non-JSON", () => {
      expect(parseJsonSafe("hello world")).toBeNull()
    })

    it("should return null for truncated JSON", () => {
      expect(parseJsonSafe('{"a":')).toBeNull()
    })

    it("should return null for empty string", () => {
      expect(parseJsonSafe("")).toBeNull()
    })

    it("should parse JSON numbers", () => {
      expect(parseJsonSafe("42")).toBe(42)
    })

    it("should parse JSON null", () => {
      expect(parseJsonSafe("null")).toBeNull()
    })

    it("should parse JSON boolean", () => {
      expect(parseJsonSafe("true")).toBe(true)
    })
  })

  describe("buildOverviewMarkdown", () => {
    it("should generate overview with stats", () => {
      const status: CodegraphStatusResult = {
        stats: { files: 10, nodes: 200, edges: 150, languages: ["TypeScript"] },
        dbSize: "1.2MB",
        indexedAt: "2025-01-01",
      }
      const md = buildOverviewMarkdown("my-project", status)
      expect(md).toContain("# my-project — Code Architecture Overview")
      expect(md).toContain("- Files: 10")
      expect(md).toContain("- Nodes: 200")
      expect(md).toContain("- Edges: 150")
      expect(md).toContain("- Languages: TypeScript")
      expect(md).toContain("- DB Size: 1.2MB")
      expect(md).toContain("- Indexed At: 2025-01-01")
      expect(md).toContain("Auto-generated by kb_ingest_codegraph")
    })

    it("should handle stats at top level (no nested stats)", () => {
      const status: CodegraphStatusResult = {
        fileCount: 5,
        nodeCount: 100,
        edgeCount: 50,
      }
      const md = buildOverviewMarkdown("proj", status)
      expect(md).toContain("- Files: 5")
      expect(md).toContain("- Nodes: 100")
      expect(md).toContain("- Edges: 50")
    })

    it("should include language breakdown table", () => {
      const status: CodegraphStatusResult = {
        languageBreakdown: [
          { language: "TypeScript", files: 8, nodes: 120 },
          { language: "Python", files: 3, nodes: 40 },
        ],
      }
      const md = buildOverviewMarkdown("proj", status)
      expect(md).toContain("## Languages")
      expect(md).toContain("| Language | Files | Nodes |")
      expect(md).toContain("| TypeScript | 8 | 120 |")
      expect(md).toContain("| Python | 3 | 40 |")
    })

    it("should include node distribution from nodeKinds object", () => {
      const status: CodegraphStatusResult = {
        nodeKinds: { function: 50, class: 20, variable: 30 },
      }
      const md = buildOverviewMarkdown("proj", status)
      expect(md).toContain("## Node Distribution")
      expect(md).toContain("| function | 50 |")
      expect(md).toContain("| class | 20 |")
    })

    it("should include node distribution from kindBreakdown array", () => {
      const status: CodegraphStatusResult = {
        kindBreakdown: [
          { kind: "function", count: 10 },
          { kind: "class", count: 5 },
        ],
      }
      const md = buildOverviewMarkdown("proj", status)
      expect(md).toContain("| function | 10 |")
      expect(md).toContain("| class | 5 |")
    })

    it("should handle languages_detail field", () => {
      const status: CodegraphStatusResult = {
        languages_detail: [
          { name: "Rust", fileCount: 4, nodeCount: 80 },
        ],
      }
      const md = buildOverviewMarkdown("proj", status)
      expect(md).toContain("| Rust | 4 | 80 |")
    })
  })

  describe("buildModuleMarkdown", () => {
    it("should generate per-file breakdown", () => {
      const status: CodegraphStatusResult = { nodeCount: 100 }
      const files: CodegraphFileResult[] = [
        { path: "src/index.ts", language: "TypeScript", nodeCount: 30, classes: ["App"], functions: ["main"] },
      ]
      const md = buildModuleMarkdown("proj", status, files)
      expect(md).toContain("# proj — Module Breakdown")
      expect(md).toContain("## src/index.ts")
      expect(md).toContain("- Language: TypeScript")
      expect(md).toContain("- Node count: 30")
      expect(md).toContain("- Classes: App")
      expect(md).toContain("- Functions: main")
    })

    it("should use filePath or name as fallback", () => {
      const files: CodegraphFileResult[] = [
        { filePath: "lib/utils.ts", language: "TypeScript", nodeCount: 5 },
      ]
      const md = buildModuleMarkdown("proj", {} as any, files)
      expect(md).toContain("## lib/utils.ts")
    })

    it("should show exports when present", () => {
      const files: CodegraphFileResult[] = [
        { path: "mod.ts", language: "TS", exports: ["foo", "bar"] },
      ]
      const md = buildModuleMarkdown("p", {} as any, files)
      expect(md).toContain("- Exports: foo, bar")
    })

    it("should extract symbols into classes/functions/exports", () => {
      const files: CodegraphFileResult[] = [
        {
          path: "sym.ts",
          language: "TS",
          symbols: [
            { name: "MyClass", kind: "class", exported: true },
            { name: "helper", kind: "function", exported: false },
            { name: "util", kind: "method", exported: true },
          ],
        },
      ]
      const md = buildModuleMarkdown("p", {} as any, files)
      expect(md).toContain("- Classes: MyClass")
      expect(md).toContain("- Functions: helper, util")
      expect(md).toContain("- Exports: MyClass, util")
    })

    it("should handle empty files array", () => {
      const md = buildModuleMarkdown("p", {} as any, [])
      expect(md).toContain("# p — Module Breakdown")
      expect(md).toContain("Auto-generated by kb_ingest_codegraph")
    })

    it("should handle non-array files", () => {
      const md = buildModuleMarkdown("p", {} as any, null as any)
      expect(md).toContain("No file data available from codegraph.")
    })
  })

  describe("buildSymbolMarkdown", () => {
    it("should include entry points", () => {
      const ctx: CodegraphContextResult = {
        entryPoints: [
          { name: "main", kind: "function", file: "index.ts", line: 10 },
        ],
      }
      const md = buildSymbolMarkdown("proj", "main", ctx)
      expect(md).toContain("# proj — Symbol Analysis: main")
      expect(md).toContain("## Entry Points")
      expect(md).toContain("- main (function) at index.ts:10")
    })

    it("should include code blocks", () => {
      const ctx: CodegraphContextResult = {
        codeBlocks: [
          { file: "app.ts", startLine: 1, endLine: 5, language: "typescript", content: "const x = 1" },
        ],
      }
      const md = buildSymbolMarkdown("proj", "app", ctx)
      expect(md).toContain("## Code Blocks")
      expect(md).toContain("### app.ts:1-5")
      expect(md).toContain("```typescript")
      expect(md).toContain("const x = 1")
    })

    it("should include summary when present", () => {
      const ctx: CodegraphContextResult = { summary: "This is a test summary" }
      const md = buildSymbolMarkdown("p", "q", ctx)
      expect(md).toContain("## Summary")
      expect(md).toContain("This is a test summary")
    })

    it("should include key symbols", () => {
      const ctx: CodegraphContextResult = {
        symbols: [
          { name: "foo", kind: "function", signature: "(x: number): void", exported: true },
        ],
      }
      const md = buildSymbolMarkdown("p", "foo", ctx)
      expect(md).toContain("### foo (function)")
      expect(md).toContain("- Signature: `(x: number): void`")
      expect(md).toContain("- Exported: true")
    })

    it("should include dependencies", () => {
      const ctx: CodegraphContextResult = {
        dependencies: ["lodash", { path: "utils.ts" }],
      }
      const md = buildSymbolMarkdown("p", "dep", ctx)
      expect(md).toContain("## Dependencies")
      expect(md).toContain("- lodash")
      expect(md).toContain("- utils.ts")
    })

    it("should include stats", () => {
      const ctx: CodegraphContextResult = {
        stats: { nodes: 10, edges: 5, files: 3, codeSize: 1024 },
      }
      const md = buildSymbolMarkdown("p", "q", ctx)
      expect(md).toContain("Nodes: 10, Edges: 5, Files: 3, Code Size: 1024")
    })

    it("should handle empty context", () => {
      const md = buildSymbolMarkdown("p", "q", {})
      expect(md).toContain("# p — Symbol Analysis: q")
      expect(md).toContain("Raw Context")
      expect(md).toContain("Auto-generated by kb_ingest_codegraph")
    })
  })

  describe("runCodegraph", () => {
    const originalSpawn = Bun.spawn
    let spawnCalls: { args: string[]; cwd: string; env: Record<string, string> }[] = []

    beforeEach(() => {
      spawnCalls = []
    })

    afterEach(() => {
      Bun.spawn = originalSpawn
    })

    function mockSpawn(stdout: string, stderr: string, exitCode: number) {
      Bun.spawn = mock((args: string[], opts: any) => {
        spawnCalls.push({ args, cwd: opts.cwd, env: opts.env })
        return {
          exited: Promise.resolve(exitCode),
          stdout: new ReadableStream({
            start(controller) {
              controller.enqueue(new TextEncoder().encode(stdout))
              controller.close()
            },
          }),
          stderr: new ReadableStream({
            start(controller) {
              controller.enqueue(new TextEncoder().encode(stderr))
              controller.close()
            },
          }),
          kill() {},
        } as any
      }) as any
    }

    it("should execute codegraph CLI with args", async () => {
      mockSpawn('{"nodes": 10}', "", 0)
      const result = await runCodegraph(["status", "--json"], "/tmp/proj", 5000)
      expect(result.exitCode).toBe(0)
      expect(result.stdout).toBe('{"nodes": 10}')
      expect(spawnCalls[0].args[0]).toBe("codegraph")
      expect(spawnCalls[0].args[1]).toBe("status")
      expect(spawnCalls[0].cwd).toBe("/tmp/proj")
    })

    it("should handle non-zero exit code", async () => {
      mockSpawn("", "error: not initialized", 1)
      const result = await runCodegraph(["status"], "/tmp/proj", 5000)
      expect(result.exitCode).toBe(1)
      expect(result.stderr).toContain("not initialized")
    })
  })

  describe("extractKeywords", () => {
    it("should include project name", () => {
      const kw = extractKeywords("my-app", {} as any)
      expect(kw).toContain("my-app")
    })

    it("should include languages from stats", () => {
      const status = { stats: { languages: ["TypeScript", "Python"] } } as any
      const kw = extractKeywords("proj", status)
      expect(kw).toContain("TypeScript")
      expect(kw).toContain("Python")
    })

    it("should include directory names from files", () => {
      const files: CodegraphFileResult[] = [
        { path: "src/index.ts" },
        { path: "lib/utils.ts" },
        { path: "src/app.ts" },
      ]
      const kw = extractKeywords("proj", {} as any, files)
      expect(kw).toContain("src")
      expect(kw).toContain("lib")
    })

    it("should limit to 12 keywords", () => {
      const kw = extractKeywords("proj", {} as any)
      expect(kw.length).toBeLessThanOrEqual(12)
    })
  })

  describe("extractRelatedFiles", () => {
    it("should extract file paths", () => {
      const files: CodegraphFileResult[] = [
        { path: "src/a.ts" },
        { filePath: "src/b.ts" },
        { name: "src/c.ts" },
      ]
      expect(extractRelatedFiles(files)).toEqual(["src/a.ts", "src/b.ts", "src/c.ts"])
    })

    it("should filter empty paths", () => {
      const files: CodegraphFileResult[] = [{ path: "" }, {} as any]
      expect(extractRelatedFiles(files)).toEqual([])
    })

    it("should handle non-array input", () => {
      expect(extractRelatedFiles(null as any)).toEqual([])
      expect(extractRelatedFiles(undefined as any)).toEqual([])
    })

    it("should limit to 50 files", () => {
      const files = Array.from({ length: 60 }, (_, i) => ({ path: `file${i}.ts` }))
      expect(extractRelatedFiles(files)).toHaveLength(50)
    })
  })
})
