import { IncomingMessage, ServerResponse } from "node:http"
import { json, parseBody } from "./helpers.js"
import { existsSync } from "node:fs"
import { basename } from "node:path"
import { writeDoc } from "../storage/index.js"
import { createLogger } from "../utils/logger.js"

const logger = createLogger("http:codegraph")

interface SpawnResult {
  stdout: string
  stderr: string
  exitCode: number
}

async function runCodegraph(args: string[], cwd: string, timeoutMs: number): Promise<SpawnResult> {
  const proc = Bun.spawn(["codegraph", ...args], {
    cwd,
    stdout: "pipe",
    stderr: "pipe",
    env: { ...process.env },
  })

  const exitCode = await Promise.race([
    proc.exited,
    new Promise<number>((_, reject) =>
      setTimeout(() => {
        proc.kill()
        reject(new Error(`codegraph timed out after ${timeoutMs}ms`))
      }, timeoutMs),
    ),
  ])

  const stdout = await new Response(proc.stdout).text()
  const stderr = await new Response(proc.stderr).text()

  return { stdout, stderr, exitCode }
}

function parseJsonSafe(raw: string): unknown {
  try {
    return JSON.parse(raw)
  } catch {
    return null
  }
}

function buildOverviewMarkdown(projectName: string, status: any): string {
  const lines: string[] = []
  lines.push(`# ${projectName} — Code Architecture Overview`)
  lines.push("")
  const stats = status.stats || status
  lines.push("## Stats")
  lines.push(`- Files: ${stats.files ?? stats.fileCount ?? "N/A"}`)
  lines.push(`- Nodes: ${stats.nodes ?? stats.nodeCount ?? "N/A"}`)
  lines.push(`- Edges: ${stats.edges ?? stats.edgeCount ?? "N/A"}`)
  if (stats.languages) lines.push(`- Languages: ${Array.isArray(stats.languages) ? stats.languages.join(", ") : stats.languages}`)
  if (stats.dbSize) lines.push(`- DB Size: ${stats.dbSize}`)
  lines.push("")
  lines.push("## Raw Status")
  lines.push("```json")
  lines.push(JSON.stringify(status, null, 2))
  lines.push("```")
  lines.push("")
  lines.push("---")
  lines.push("> Auto-generated by kb_ingest_codegraph")
  return lines.join("\n")
}

function buildModuleMarkdown(projectName: string, status: any, files: any[]): string {
  const lines: string[] = []
  lines.push(`# ${projectName} — Module Breakdown`)
  lines.push("")
  if (Array.isArray(files)) {
    for (const file of files) {
      const fp = file.path || file.filePath || file.name || "unknown"
      lines.push(`## ${fp}`)
      lines.push(`- Language: ${file.language || "unknown"}`)
      lines.push(`- Node count: ${file.nodeCount ?? file.nodes ?? file.symbolCount ?? 0}`)
      lines.push("")
    }
  }
  lines.push("## Raw Data")
  lines.push("```json")
  lines.push(JSON.stringify({ status, files }, null, 2))
  lines.push("```")
  lines.push("")
  lines.push("---")
  lines.push("> Auto-generated by kb_ingest_codegraph")
  return lines.join("\n")
}

function buildSymbolMarkdown(projectName: string, query: string, context: any): string {
  const lines: string[] = []
  lines.push(`# ${projectName} — Symbol Analysis: ${query}`)
  lines.push("")
  if (context.summary) {
    lines.push("## Summary")
    lines.push(context.summary)
    lines.push("")
  }
  if (context.symbols && Array.isArray(context.symbols)) {
    lines.push("## Key Symbols")
    for (const sym of context.symbols.slice(0, 30)) {
      lines.push(`### ${sym.name} (${sym.kind || "unknown"})`)
      if (sym.signature) lines.push(`- Signature: \`${sym.signature}\``)
      lines.push("")
    }
  }
  lines.push("## Raw Context")
  lines.push("```json")
  lines.push(JSON.stringify(context, null, 2))
  lines.push("```")
  lines.push("")
  lines.push("---")
  lines.push("> Auto-generated by kb_ingest_codegraph")
  return lines.join("\n")
}

export async function handleCodegraphRoutes(
  req: IncomingMessage,
  res: ServerResponse,
  url: URL,
): Promise<boolean> {
  if (url.pathname !== "/api/codegraph/ingest" || req.method !== "POST") return false

  const body = (await parseBody(req, res)) as Record<string, any> | null
  if (body === null) return true

  const project_path = body.project_path
  const scope = body.scope || "overview"
  const query = body.query
  const force_reindex = body.force_reindex || false

  if (!project_path || typeof project_path !== "string") {
    json(res, { error: "project_path is required" }, 400)
    return true
  }

  if (!["overview", "module", "symbol"].includes(scope)) {
    json(res, { error: "scope must be 'overview', 'module', or 'symbol'" }, 400)
    return true
  }

  if (!existsSync(project_path)) {
    json(res, { error: "Project path does not exist", path: project_path }, 400)
    return true
  }

  try {
    const hasCodegraphDir = existsSync(`${project_path}/.codegraph`)

    if (force_reindex || !hasCodegraphDir) {
      if (!hasCodegraphDir) {
        const initResult = await runCodegraph(["init", "-i"], project_path, 60000)
        if (initResult.exitCode !== 0) {
          json(res, { error: "codegraph init failed", stderr: initResult.stderr }, 500)
          return true
        }
      }
      if (force_reindex) {
        await runCodegraph(["index", "-f"], project_path, 60000)
      }
    }

    const projectName = basename(project_path)
    let markdown = ""
    let keywords: string[] = [projectName]
    let relatedFiles: string[] = []

    if (scope === "overview") {
      const result = await runCodegraph(["status", "--json"], project_path, 30000)
      if (result.exitCode !== 0) {
        json(res, { error: "codegraph status failed", stderr: result.stderr }, 500)
        return true
      }
      const statusData: any = parseJsonSafe(result.stdout) || { raw: result.stdout }
      markdown = buildOverviewMarkdown(projectName, statusData)
      keywords = [projectName, ...(statusData.stats?.languages || [])]
    } else if (scope === "module") {
      const [statusResult, filesResult] = await Promise.all([
        runCodegraph(["status", "--json"], project_path, 30000),
        runCodegraph(["files", "--json"], project_path, 30000),
      ])
      if (statusResult.exitCode !== 0) {
        json(res, { error: "codegraph status failed", stderr: statusResult.stderr }, 500)
        return true
      }
      const statusData: any = parseJsonSafe(statusResult.stdout) || { raw: statusResult.stdout }
      let filesData: any = parseJsonSafe(filesResult.stdout) || []
      if (!Array.isArray(filesData) && (filesData as any).files) filesData = (filesData as any).files
      markdown = buildModuleMarkdown(projectName, statusData, filesData)
      relatedFiles = Array.isArray(filesData)
        ? (filesData as any[]).map((f: any) => f.path || f.filePath || f.name || "").filter((p: string) => p).slice(0, 50)
        : []
    } else {
      const taskQuery = query || `${projectName} project overview`
      const result = await runCodegraph(["context", taskQuery, "--format", "json"], project_path, 30000)
      if (result.exitCode !== 0) {
        json(res, { error: "codegraph context failed", stderr: result.stderr }, 500)
        return true
      }
      const contextData: any = parseJsonSafe(result.stdout) || { raw: result.stdout, summary: result.stdout.slice(0, 500) }
      markdown = buildSymbolMarkdown(projectName, taskQuery, contextData)
    }

    const doc = writeDoc(
      {
        title: `CodeGraph: ${projectName} - ${scope} analysis`,
        tags: ["code-index", "codegraph", scope, "auto-ingested"],
        keywords,
        intent: `Code structure analysis (${scope}) for ${projectName}`,
        project_description: projectName,
        project_path,
        source_project: projectName,
        related_files: relatedFiles,
      },
      markdown,
    )

    json(res, {
      saved: true,
      id: doc.id,
      title: doc.title,
      scope,
      project_name: projectName,
      keywords,
      related_files_count: relatedFiles.length,
    })
    return true
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e)
    logger.error("codegraph ingest error:", msg)
    json(res, { error: "codegraph execution failed", detail: msg }, 500)
    return true
  }
}
